modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"


[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://modrinth.com/project/foxium" #optional
issueTrackerURL="https://github.com/1foxy2/foxium/issues" #optional
logoFile="logo.png" #optional
credits="some improvements was taken from radium" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[mixins]]
config="lithium.mixins.json"

[modproperties.modmenu]
links=[
    "mod_menu.original=https://modrinth.com/mod/lithium",
    "mod_menu.wiki=https://github.com/1foxy2/foxium/wiki"
]
sources="https://github.com/1foxy2/foxium" # a link to sources of the mod

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
